apiVersion: v1
kind: Pod
metadata:
  name: nodejs-pod
  labels:
    app: nodejs-app
spec:
  containers:
  - name: nodejs-app
    image: nodejs-app
    imagePullPolicy: Never
    ports:
    - containerPort: 3000

